server:
    port: 8080

spring:
    datasource:
        url: jdbc:mysql://82.157.137.229:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: thoughts-beta
        password: thoughts-beta

mybatis:
    mapper-locations:
        - classpath:mapper/*.xml
        - classpath*:com/**/mapper/*.xml


